{
 "title": "MQTT Hackathon Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Message Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mqtt_message_counter" }
   ]
  },
  {
   "title": "Throughput per topic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "rate(mqtt_message_counter[1m])", "legendFormat": "{{topic}}" }
   ]
  },
  {
   "title": "Throughput requests/sec",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(topic)(rate(mqtt_message_counter[1m]))"
    }
   ]
  }
 ]
}