global:
  # How frequently to scrape targets by default.
  scrape_interval: 5s

  # How long until a scrape request times out.
  scrape_timeout: 5s

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
# A list of scrape configurations.
scrape_configs:
- job_name: mqtt-hackathon
  metrics_path: "/metrics"

  static_configs:
  - targets: ['127.0.0.1:8080']
